### PR TITLE
Simplify example setup

### PR DESCRIPTION
**Pull request by ryyppy**
- Inlined BS compiler flag in package.json scripts (user doesn't need to do the export logic)
- Renamed `examples/typescript-example` to `examples/typescript-react-example`

### CODE REVIEW

**Comment by cristianoc** [comment]
One issue with inlining is that editor integration needs BS_CMT_POST_PROCESS_CMD to be set up, and now the instructions don't specify how to set it up.

**Comment by cristianoc** [comment]
Perhaps one can simply add a line explaining how to set up editor integration.

**Comment by cem2ran** [comment]
Maybe add this in a `.envrc` file? Would help people who use https://direnv.net or have the vscode extension installed: https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-direnv

**Comment by cristianoc** [comment]
Meanwhile, `--setProjectRoot` is not needed anymore: https://github.com/cristianoc/genFlow/commit/4043415f8fad9e563221bdd0cff77199332c6a13.

A consequence of that is that `BS_CMT_POST_PROCESS_CMD` can be set just once, and not on a per-project basis.

**Comment by ryyppy** [comment]
> One issue with inlining is that editor integration needs BS_CMT_POST_PROCESS_CMD to be set up, and now the instructions don't specify how to set it up.

I would argue that anyone who is interested to set it up, will automatically look into the `package.json`. Maybe I am biased, but that's usually my first intuition to get into a project.

I don't like the fact that developers are required to maintain their env variables outside of a package.json, it is an unnecessary potential error, which can be mitigated by just using `npm run` scripts. E.g. for `reason-conf-2019`, I don't want to bother our JS dev to mess around with that env hooks, it's just confusing and hard to troubleshoot.

@cem2ran 
> Maybe add this in a .envrc file? Would help people who use https://direnv.net or have the vscode extension installed...

That would be an option, but this makes assumptions about the setup of the developer tooling. Not everyone is using this, it just adds friction for migration.

**Pull request merged**
